#!/usr/bin/env python

"""Traverses a project directory generated by Keras Tuner
and create a CSV file consumable by HiPlot """

import sys
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import json
import hiplot 

def get_tuner_summary(project_path):
    target_file = (
        "trial.json"  # result of each trial is saved by keras-tuner as a json file
    )
    summary = []
    for root, dirs, files in os.walk(project_path): 
        if target_file in files:
            with open(root + '/' + target_file, 'r') as handle:
                trial_json = handle.read()
            trial_full = json.loads(trial_json)    
            trial_simple = trial_full["hyperparameters"][
                "values"
            ]    # extract hyperparameters used for that trial
            trial_simple["score"] = trial_full[
                "score"
            ]    # output is similar as {'learning_rate': 0.0001, 'frozen_layers': 24, 'score': 0.03169512003660202}
            summary.append(trial_simple)
    return summary


if __name__ == "__main__":
    kt_project_path = sys.argv[1] 
    save_as = os.path.join(kt_project_path, "hiplot.csv")
    tuner_summary = get_tuner_summary(kt_project_path)  
    hiplot.Experiment.from_iterable(tuner_summary).to_csv(save_as)
    # hip.Experiment.from_iterable(visualization_data).display()  # could directly display if running in a notebook
    print("HiPlot data saved to:", os.path.abspath(save_as))